#!/bin/bash

PSQL="psql --username=freecodecamp --dbname=number_guess -t --no-align -c"

secret_number=$(( RANDOM % 1000 + 1 ))
number_of_guesses=0

printf "Enter your username:"
read -r username

escaped_username=$(printf "%s" "$username" | sed "s/'/''/g")
user_info=$($PSQL "SELECT username, games_played, best_game FROM users WHERE username = '$escaped_username';")

if [[ -z "$user_info" ]]; then
  $PSQL "INSERT INTO users(username, games_played, best_game) VALUES ('$escaped_username', 0, NULL);"
  printf "Welcome, %s! It looks like this is your first time here.\n" "$username"
else
  IFS='|' read -r existing_username games_played best_game <<< "$user_info"
  printf "Welcome back, %s! You have played %s games, and your best game took %s guesses.\n" "$existing_username" "$games_played" "$best_game"
fi

printf "Guess the secret number between 1 and 1000:"
while true; do
  read -r guess

  if [[ ! "$guess" =~ ^[0-9]+$ ]]; then
    printf "That is not an integer, guess again:\n"
    continue
  fi

  (( number_of_guesses += 1 ))

  if (( guess < secret_number )); then
    printf "It's higher than that, guess again:\n"
  elif (( guess > secret_number )); then
    printf "It's lower than that, guess again:\n"
  else
    break
  fi
done

printf "You guessed it in %s tries. The secret number was %s. Nice job!\n" "$number_of_guesses" "$secret_number"

if [[ -z "$user_info" ]]; then
  $PSQL "UPDATE users SET games_played = 1, best_game = $number_of_guesses WHERE username = '$escaped_username';"
else
  $PSQL "UPDATE users SET games_played = games_played + 1, best_game = CASE WHEN best_game IS NULL OR $number_of_guesses < best_game THEN $number_of_guesses ELSE best_game END WHERE username = '$escaped_username';"
fi

